/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_crayfish_ndkproject_Base64Util */

#ifndef _Included_com_crayfish_ndkproject_Base64Util
#define _Included_com_crayfish_ndkproject_Base64Util
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_crayfish_ndkproject_Base64Util
 * Method:    b64_encode
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_crayfish_ndkproject_Base64Util_b64_1encode
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_crayfish_ndkproject_Base64Util
 * Method:    b64_decode
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_crayfish_ndkproject_Base64Util_b64_1decode
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
