/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_crayfish_ndkproject_NdkTest */

#ifndef _Included_com_crayfish_ndkproject_NdkTest
#define _Included_com_crayfish_ndkproject_NdkTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_crayfish_ndkproject_NdkTest
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_crayfish_ndkproject_NdkTest_getString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
