/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_crayfish_ndkproject_PlusJni */

#ifndef _Included_com_crayfish_ndkproject_PlusJni
#define _Included_com_crayfish_ndkproject_PlusJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_crayfish_ndkproject_PlusJni
 * Method:    plusNumbers
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_crayfish_ndkproject_PlusJni_plusNumbers
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
