/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_crayfish_ndkproject_AESjni */

#ifndef _Included_com_crayfish_ndkproject_AESjni
#define _Included_com_crayfish_ndkproject_AESjni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_crayfish_ndkproject_AESjni
 * Method:    myEncrypt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_crayfish_ndkproject_AESjni_myEncrypt
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_crayfish_ndkproject_AESjni
 * Method:    myDecrypt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_crayfish_ndkproject_AESjni_myDecrypt
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
