/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_crayfish_ndkproject_AESUtil */

#ifndef _Included_com_crayfish_ndkproject_AESUtil
#define _Included_com_crayfish_ndkproject_AESUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_crayfish_ndkproject_AESUtil
 * Method:    encrypt
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_crayfish_ndkproject_AESUtil_encrypt
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_crayfish_ndkproject_AESUtil
 * Method:    decrypt
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_crayfish_ndkproject_AESUtil_decrypt
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
